# thanks everyone for using the plugin!
# website: https://baston1337.me

# where player data will be saved
storage:
  type: 'mysql' # mysql or yml
  mysql:
    host: 'localhost'
    port: '3306'
    user: 'root'
    pass: ''
    database: 'bkitpvp'


# all editable messages
msg:
  build:
    permission: '&cYou are not allowed for this.'
    console: '&cYou need to be a player for this. '